name: Deploy ADF to QA

on:
  push:
    branches:
      - adf_publish  # or your release branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ADF resources
      uses: Azure/data-factory-deploy-action@v1.2.0
      with:
        resourceGroupName: 'Test-adf'
        dataFactoryName: 'QA-testing-adf'
        armTemplateFile: './ARMTemplateForFactory.json'
        armTemplateParametersFile: './ARMTemplateParametersForFactory.json'
