name: Deploy ADF to QA

on:

  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (e.g., dev, test, prod)'
        required: true
        default: 'qa'
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      pipeline_name:
        description: 'Name of the ADF pipeline to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Az PowerShell Module
      shell: pwsh
      run: |
        Install-Module -Name Az -Force -Scope CurrentUser -AllowClobber

    - name: Explicit PowerShell Login (Workaround)
      shell: pwsh
      run: |
        $creds = $env:AZURE_CREDENTIALS | ConvertFrom-Json
        $securePassword = ConvertTo-SecureString $creds.clientSecret -AsPlainText -Force
        $psCredential = New-Object System.Management.Automation.PSCredential ($creds.clientId, $securePassword)
        Connect-AzAccount -ServicePrincipal -Credential $psCredential -Tenant $creds.tenantId -SubscriptionId $creds.subscriptionId
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ADF resources
      uses: Azure/data-factory-deploy-action@v1.2.0
      with:
        resourceGroupName: 'Test-adf'
        dataFactoryName: 'QA-testing-adf'
        armTemplateFile: './testing-adf-repo/ARMTemplateForFactory.json'
        armTemplateParametersFile: './testing-adf-repo/ARMTemplateParametersForFactory.json'

    - name: Log deployment inputs
      run: |
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo "Version: ${{ github.event.inputs.version }}"
        echo "Pipeline Name: ${{ github.event.inputs.pipeline_name }}"
