name: Migrate ADF Pipeline

on:
  workflow_dispatch:
    inputs:
      pipeline_name:
        description: 'Name of the pipeline to migrate'
        required: true
      input_source:
        description: 'Input source to update in the pipeline'
        required: true
      output_source:
        description: 'Output source to update in the pipeline'
        required: true
      target_adf:
        description: 'Target Azure Data Factory name'
        required: true

jobs:
  migrate-pipeline:
    runs-on: ubuntu-latest

    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      RESOURCE_GROUP: Test-adf
      SOURCE_ADF: QA-testing-adf

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Export pipeline JSON from source ADF
      - name: Export pipeline JSON
        run: |
          az datafactory pipeline export \
            --factory-name $SOURCE_ADF \
            --resource-group $RESOURCE_GROUP \
            --name ${{ inputs.pipeline_name }} \
            --output-path exported_pipeline.json

      # Step 4: Modify pipeline JSON
      - name: Modify pipeline JSON
        run: |
          jq '.properties.activities[].typeProperties.source.referenceName = "${{ inputs.input_source }}" |
              .properties.activities[].typeProperties.sink.referenceName = "${{ inputs.output_source }}"' \
              exported_pipeline.json > modified_pipeline.json

      # Step 5: Import pipeline JSON to target ADF
      - name: Import pipeline JSON
        run: |
          az datafactory pipeline import \
            --factory-name ${{ inputs.target_adf }} \
            --resource-group $RESOURCE_GROUP \
            --name ${{ inputs.pipeline_name }} \
            --input-path modified_pipeline.json

      # Step 6: Publish pipeline
      - name: Publish pipeline
        run: |
          az datafactory pipeline create \
            --factory-name ${{ inputs.target_adf }} \
            --resource-group $RESOURCE_GROUP \
            --name ${{ inputs.pipeline_name }} \
            --pipeline @modified_pipeline.json

      # Step 7: Show job summary
      - name: Job Summary
        run: |
          echo "Pipeline Name: ${{ inputs.pipeline_name }}"
          echo "Environment: ${{ inputs.target_adf }}"
          echo "Input Source: ${{ inputs.input_source }}"
          echo "Output Source: ${{ inputs.output_source }}"